const strings = [
  'Login successful.',
  'Listening on port {0}.',
  'Account added successfully.',
  'Account updated successfully.',
  'Account deleted successfully.',
  'Favorite added.',
  'Favorite deleted.',
  'Cart item added.',
  'Cart item deleted.',
  'Books added.',
  'Log level set. New log level is {0}',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'RESERVED',
  'Authentication not configured.',
  'Authorization not configured.',
  'Unauthorized.',
  'Login required.',
  'Incorrect username: {0}.',
  'Incorrect password.',
  'Incorrect email: {0}.',
  'At least one group is required.',
  'Login Expired.',
  '{1}',
  'Conflict: File {1} Already Exists.',
  'Account already exists.',
  'Account operation failed. Error: {0}',
  'Account does not exist.',
  'Add favorite failed. Error: {0}',
  'Delete favorite failed. Error: {0}',
  'Add to cart failed. Error: {0}',
  'Delete from cart failed. Error: {0}',
  'No color was chosen.',
  'Subtotal is required.',
  'Taxes are required.',
  'Total is required.',
  'Book list is required.',
  'Invalid JSON.',
  'Incorrect book id: {0}.',
  'Incorrect book issue: {0}.',
  'Error reading owned books. Error: {0}',
  'Add books to account failed. Error: {0}',
  'Error writing owned books. Error: {0}',
  'Error reading books.',
  'Error reading user information.',
  'Invalid reset token.',
  'An error occured while sending email. Error: {0}',
  'User not found. {0}',
  'Microservice {0} timed out. Timeout value: {1}',
  'Unknown log level {0}.',
  'Encryption error.',
];

module.exports = strings;
